/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as MyTripsRouteImport } from './routes/my-trips'
import { Route as OperatorTermsRouteImport } from './routes/operator-terms'
import { Route as OperatorsRouteImport } from './routes/operators'
import { Route as PlanTripRouteImport } from './routes/plan-trip'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AdminOperatorsRouteImport } from './routes/admin/operators'
import { Route as AdminPlansRouteImport } from './routes/admin/plans'
import { Route as DestinationsIndexRouteImport } from './routes/destinations/index'
import { Route as DestinationsSlugRouteImport } from './routes/destinations/$slug'
import { Route as OperatorIndexRouteImport } from './routes/operator/index'
import { Route as OperatorBillingRouteImport } from './routes/operator/billing'
import { Route as OperatorLeadsRouteImport } from './routes/operator/leads'
import { Route as OperatorProfileRouteImport } from './routes/operator/profile'
import { Route as OperatorSubscriptionRouteImport } from './routes/operator/subscription'
import { Route as ApiPublicWebhooksIntasendRouteImport } from './routes/api/public/webhooks/intasend'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTripsRoute = MyTripsRouteImport.update({
  id: '/my-trips',
  path: '/my-trips',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorTermsRoute = OperatorTermsRouteImport.update({
  id: '/operator-terms',
  path: '/operator-terms',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorsRoute = OperatorsRouteImport.update({
  id: '/operators',
  path: '/operators',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanTripRoute = PlanTripRouteImport.update({
  id: '/plan-trip',
  path: '/plan-trip',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOperatorsRoute = AdminOperatorsRouteImport.update({
  id: '/operators',
  path: '/operators',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlansRoute = AdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AdminRoute,
} as any)
const DestinationsIndexRoute = DestinationsIndexRouteImport.update({
  id: '/destinations/',
  path: '/destinations/',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsSlugRoute = DestinationsSlugRouteImport.update({
  id: '/destinations/$slug',
  path: '/destinations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorIndexRoute = OperatorIndexRouteImport.update({
  id: '/operator/',
  path: '/operator/',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorBillingRoute = OperatorBillingRouteImport.update({
  id: '/operator/billing',
  path: '/operator/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorLeadsRoute = OperatorLeadsRouteImport.update({
  id: '/operator/leads',
  path: '/operator/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorProfileRoute = OperatorProfileRouteImport.update({
  id: '/operator/profile',
  path: '/operator/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorSubscriptionRoute = OperatorSubscriptionRouteImport.update({
  id: '/operator/subscription',
  path: '/operator/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksIntasendRoute =
  ApiPublicWebhooksIntasendRouteImport.update({
    id: '/api/public/webhooks/intasend',
    path: '/api/public/webhooks/intasend',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/cookies': typeof CookiesRoute
  '/my-trips': typeof MyTripsRoute
  '/operator-terms': typeof OperatorTermsRoute
  '/operators': typeof OperatorsRoute
  '/plan-trip': typeof PlanTripRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/operators': typeof AdminOperatorsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/operator/billing': typeof OperatorBillingRoute
  '/operator/leads': typeof OperatorLeadsRoute
  '/operator/profile': typeof OperatorProfileRoute
  '/operator/subscription': typeof OperatorSubscriptionRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/operator/': typeof OperatorIndexRoute
  '/api/public/webhooks/intasend': typeof ApiPublicWebhooksIntasendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/cookies': typeof CookiesRoute
  '/my-trips': typeof MyTripsRoute
  '/operator-terms': typeof OperatorTermsRoute
  '/operators': typeof OperatorsRoute
  '/plan-trip': typeof PlanTripRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/operators': typeof AdminOperatorsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/operator/billing': typeof OperatorBillingRoute
  '/operator/leads': typeof OperatorLeadsRoute
  '/operator/profile': typeof OperatorProfileRoute
  '/operator/subscription': typeof OperatorSubscriptionRoute
  '/destinations': typeof DestinationsIndexRoute
  '/operator': typeof OperatorIndexRoute
  '/api/public/webhooks/intasend': typeof ApiPublicWebhooksIntasendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/cookies': typeof CookiesRoute
  '/my-trips': typeof MyTripsRoute
  '/operator-terms': typeof OperatorTermsRoute
  '/operators': typeof OperatorsRoute
  '/plan-trip': typeof PlanTripRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/operators': typeof AdminOperatorsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/operator/billing': typeof OperatorBillingRoute
  '/operator/leads': typeof OperatorLeadsRoute
  '/operator/profile': typeof OperatorProfileRoute
  '/operator/subscription': typeof OperatorSubscriptionRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/operator/': typeof OperatorIndexRoute
  '/api/public/webhooks/intasend': typeof ApiPublicWebhooksIntasendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/auth'
    | '/cookies'
    | '/my-trips'
    | '/operator-terms'
    | '/operators'
    | '/plan-trip'
    | '/privacy'
    | '/refund-policy'
    | '/reset-password'
    | '/terms'
    | '/verify-email'
    | '/admin/operators'
    | '/admin/plans'
    | '/destinations/$slug'
    | '/operator/billing'
    | '/operator/leads'
    | '/operator/profile'
    | '/operator/subscription'
    | '/destinations/'
    | '/operator/'
    | '/api/public/webhooks/intasend'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/auth'
    | '/cookies'
    | '/my-trips'
    | '/operator-terms'
    | '/operators'
    | '/plan-trip'
    | '/privacy'
    | '/refund-policy'
    | '/reset-password'
    | '/terms'
    | '/verify-email'
    | '/admin/operators'
    | '/admin/plans'
    | '/destinations/$slug'
    | '/operator/billing'
    | '/operator/leads'
    | '/operator/profile'
    | '/operator/subscription'
    | '/destinations'
    | '/operator'
    | '/api/public/webhooks/intasend'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-login'
    | '/auth'
    | '/cookies'
    | '/my-trips'
    | '/operator-terms'
    | '/operators'
    | '/plan-trip'
    | '/privacy'
    | '/refund-policy'
    | '/reset-password'
    | '/terms'
    | '/verify-email'
    | '/admin/operators'
    | '/admin/plans'
    | '/destinations/$slug'
    | '/operator/billing'
    | '/operator/leads'
    | '/operator/profile'
    | '/operator/subscription'
    | '/destinations/'
    | '/operator/'
    | '/api/public/webhooks/intasend'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AuthRoute: typeof AuthRoute
  CookiesRoute: typeof CookiesRoute
  MyTripsRoute: typeof MyTripsRoute
  OperatorTermsRoute: typeof OperatorTermsRoute
  OperatorsRoute: typeof OperatorsRoute
  PlanTripRoute: typeof PlanTripRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  DestinationsSlugRoute: typeof DestinationsSlugRoute
  OperatorBillingRoute: typeof OperatorBillingRoute
  OperatorLeadsRoute: typeof OperatorLeadsRoute
  OperatorProfileRoute: typeof OperatorProfileRoute
  OperatorSubscriptionRoute: typeof OperatorSubscriptionRoute
  DestinationsIndexRoute: typeof DestinationsIndexRoute
  OperatorIndexRoute: typeof OperatorIndexRoute
  ApiPublicWebhooksIntasendRoute: typeof ApiPublicWebhooksIntasendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-trips': {
      id: '/my-trips'
      path: '/my-trips'
      fullPath: '/my-trips'
      preLoaderRoute: typeof MyTripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator-terms': {
      id: '/operator-terms'
      path: '/operator-terms'
      fullPath: '/operator-terms'
      preLoaderRoute: typeof OperatorTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operators': {
      id: '/operators'
      path: '/operators'
      fullPath: '/operators'
      preLoaderRoute: typeof OperatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan-trip': {
      id: '/plan-trip'
      path: '/plan-trip'
      fullPath: '/plan-trip'
      preLoaderRoute: typeof PlanTripRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/operators': {
      id: '/admin/operators'
      path: '/operators'
      fullPath: '/admin/operators'
      preLoaderRoute: typeof AdminOperatorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plans': {
      id: '/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminPlansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/destinations/': {
      id: '/destinations/'
      path: '/destinations'
      fullPath: '/destinations/'
      preLoaderRoute: typeof DestinationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/$slug': {
      id: '/destinations/$slug'
      path: '/destinations/$slug'
      fullPath: '/destinations/$slug'
      preLoaderRoute: typeof DestinationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator/': {
      id: '/operator/'
      path: '/operator'
      fullPath: '/operator/'
      preLoaderRoute: typeof OperatorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator/billing': {
      id: '/operator/billing'
      path: '/operator/billing'
      fullPath: '/operator/billing'
      preLoaderRoute: typeof OperatorBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator/leads': {
      id: '/operator/leads'
      path: '/operator/leads'
      fullPath: '/operator/leads'
      preLoaderRoute: typeof OperatorLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator/profile': {
      id: '/operator/profile'
      path: '/operator/profile'
      fullPath: '/operator/profile'
      preLoaderRoute: typeof OperatorProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator/subscription': {
      id: '/operator/subscription'
      path: '/operator/subscription'
      fullPath: '/operator/subscription'
      preLoaderRoute: typeof OperatorSubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/intasend': {
      id: '/api/public/webhooks/intasend'
      path: '/api/public/webhooks/intasend'
      fullPath: '/api/public/webhooks/intasend'
      preLoaderRoute: typeof ApiPublicWebhooksIntasendRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminOperatorsRoute: typeof AdminOperatorsRoute
  AdminPlansRoute: typeof AdminPlansRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminOperatorsRoute: AdminOperatorsRoute,
  AdminPlansRoute: AdminPlansRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AuthRoute: AuthRoute,
  CookiesRoute: CookiesRoute,
  MyTripsRoute: MyTripsRoute,
  OperatorTermsRoute: OperatorTermsRoute,
  OperatorsRoute: OperatorsRoute,
  PlanTripRoute: PlanTripRoute,
  PrivacyRoute: PrivacyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  DestinationsSlugRoute: DestinationsSlugRoute,
  OperatorBillingRoute: OperatorBillingRoute,
  OperatorLeadsRoute: OperatorLeadsRoute,
  OperatorProfileRoute: OperatorProfileRoute,
  OperatorSubscriptionRoute: OperatorSubscriptionRoute,
  DestinationsIndexRoute: DestinationsIndexRoute,
  OperatorIndexRoute: OperatorIndexRoute,
  ApiPublicWebhooksIntasendRoute: ApiPublicWebhooksIntasendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
